controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
HomeController:
    path: /bonjour
    controller: App\Controller\HomeController::sayHello
